apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-bot-app
  namespace: argocd
spec:
  project: gosu-main
  source:
    repoURL: 'https://git.gosu-devops.ru/gosu/devops'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://default.svc'
    namespace: weather-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
