[master]
k8s-master ansible_host=192.168.181.133 ansible_user=gosu

[worker]
k8s-worker ansible_host=192.168.181.134 ansible_user=gosu

[k8s_cluster:children]
master
worker

[all:vars]
ansible_python_interpreter=/usr/bin/python3
