apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: weather-bot-secret
  namespace: weather-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: weather-bot-secret
    creationPolicy: Owner
  data:
  - secretKey: TELEGRAM_TOKEN
    remoteRef:
      key: secret/weather-bot/config
      property: telegram_token
  - secretKey: WEATHER_API_KEY
    remoteRef:
      key: secret/weather-bot/config
      property: weather_api_key
