apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-bot
  namespace: weather-bot
spec:
  selector:
    matchLabels:
      app: weather-bot
  endpoints:
  - port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
