---
- name: Configure Docker on all nodes
  hosts: all
  become: yes
  roles:
    - docker

- name: Configure containerd on worker node
  hosts: worker
  become: yes
  roles:
    - containerd

- name: Setup Gitea Runner on worker node
  hosts: worker
  become: yes
  roles:
    - gitea-runner
