gitlabUrl: http://192.168.0.199/
runnerToken: "glrt-GewzbxTtIUXWT6_7igJ-9G86MQpwOjEKdDozCnU6MQ8.01.171qnzxwl"

rbac:
  create: true
  rules:
   - apiGroups: ["*"]
     resources: ["*"]
     verbs: ["*"]
  clusterWideAccess: true

serviceAccount:
  create: true
  name: "runner"

runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "ubuntu:22.04"
        service_account = "runner"
        privileged = true
        
        # Добавляем hosts, чтобы резолвился gitlab.local (если нужно)
        [[runners.kubernetes.host_aliases]]
          ip = "192.168.0.199"
          hostnames = ["gitlab.local"]
        
        # Монтируем docker.sock для DinD
        [[runners.kubernetes.volumes.host_path]]
          name = "docker"
          mount_path = "/var/run/docker.sock"
          read_only = false
          host_path = "/var/run/docker.sock"