apiVersion: v1
kind: Secret
metadata:
  name: weather-bot-secret
type: Opaque
stringData:
  TELEGRAM_TOKEN: "8451074510:AAEV65ypcxPTcmkNvjT60PjM8qL7aRFZIp0"
  WEATHER_API_KEY: "d8ea06ba38a246d9a0a202927260905"